### PR TITLE
feat(behavior_path_planner): update pull_over module

### PR DESCRIPTION
**Pull request by kosuke55**
## PR Type

- New Feature

## Related Links

https://github.com/autowarefoundation/autoware.universe/pull/873

## Description

launcher for https://github.com/autowarefoundation/autoware.universe/pull/873
image

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
@kosuke55 can you share the rviz screen with this PR config?

**Comment by kosuke55** [comment]
@yukkysaito 
It is not good because putting the folder in DebugMarker.
I would also like to discuss the location of modified_goal.
image

**Comment by kosuke55** [comment]
@yukkysaito updated config
Screenshot from 2022-07-08 20-20-39

**Review by yukkysaito — DISMISSED** [review]
LGTM

**Comment by yukkysaito** [comment]
@kosuke55 Thank you :+1:

**Comment by kosuke55** [comment]
@yukkysaito 
sorry, I pushed again and it dismiss the review. please approve again

**Review by shmpwk — APPROVED** [review]
could you change https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/rviz/autoware.rviz also?

**Comment by kosuke55** [comment]
@shmpwk 
thanks, yes here https://github.com/autowarefoundation/autoware_launch/pull/58

**Comment by shmpwk** [comment]
thank you!!! @kosuke55

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
