### PR TITLE
chore(behavior_velocity): update latest params

### PR DESCRIPTION
**Pull request by taikitanaka3**
Signed-off-by: tanaka3 <ttatcoder@outlook.jp>

## PR Type

- Improvement

sync latest universe params

## Related Links

- https://github.com/autowarefoundation/autoware.universe/pull/932 (sync)
- https://github.com/autowarefoundation/autoware.universe/pull/620 (update)

## Description
sync and update to latest universe params 
image

## Review Procedure

take a look at

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by 0x126** [comment]
@taikitanaka3 Some paramters differ from https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_velocity_planner/config/occlusion_spot.param.yaml.
I think it should be the same. Can you explain why ?

**Comment by taikitanaka3** [comment]
@0x126 
it is based on the experiment param so I changed here.(sorry some parameters are not yet updated)
https://github.com/tier4/autoware_launch.x2/blob/experiment/v1.0.1_occlusion_spot/planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml
here is a parameter to change
```
        max_slow_down_jerk: -0.3            # [m/s^3] minimum jerk deceleration for safe brake.
        max_slow_down_accel: -1.5           # [m/s^2] minimum accel deceleration for safe brake.
        max_lateral_distance: 5.0        # [m] buffer around the ego path used to build the detection area.
      grid:
        free_space_max: 43  # [-] maximum value of a free space cell in the occupancy grid
        occupied_min: 57    # [-] minimum value of an occupied cell in the occupancy grid
```

**Comment by taikitanaka3** [comment]
and this param is missing while changing to use `universe yaml file` to  `autoware_launcher yaml` file
https://github.com/autowarefoundation/autoware.universe/blob/93d95dd63a9d84bdca4fd87acb4b200098dd8bf3/planning/behavior_velocity_planner/config/occlusion_spot.param.yaml#L7

**Comment by h-ohta** [comment]
LGTM for stopline

**Review by 0x126 — APPROVED** [review]

**Pull request merged**
