### PR TITLE
feat: sync awf perception launch

### PR DESCRIPTION
**Pull request by yukkysaito**
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>

## PR Type

- Improvement

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by miursh** [comment]
@yukkysaito 
There should be `pointcloud_map_filter.launch.py` added to `perception_launch/launch/object_recognition/detection/` and `pointcloud_map_filter.param.yaml` to `perception_launch/config/object_recognition/detection/`
Could you add those 2 files? :bow:

**Comment by yukkysaito** [comment]
@miursh Thank you for comment.
This is intentional and I think it is no need. 
because we will merge between this perception launch and awf/tier4_preception_launch.

**Comment by miursh** [comment]
Ah I understand. It was my mistake. As long as it refers to tier4_perception_launch, no problem.

**Comment by tkimura4** [comment]
@yukkysaito 

These two flies is needed in autoware_launch because  the `use_down_sample_filter` prameter is different for each products.

**Comment by yukkysaito** [comment]
>These two flies is needed in autoware_launch because the use_down_sample_filter prameter is different for each products.

@tkimura4 
I see.
@miursh sorry, I thought the same for each product. If it is difference, I have to add these files :pray:

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
