### PR TITLE
feat(rviz): add behavior path debug markers

### PR DESCRIPTION
**Pull request by satoshi-ota**
Signed-off-by: satoshi-ota <satoshi.ota928@gmail.com>

## PR Type

- Improvement

## Related Links

- https://github.com/autowarefoundation/autoware.universe/pull/1711

## Description

- add debug markers of following behavior path modules
  - avoidance
  - lane change
  - lane following
  - pull over
  - pull out
  - side shift

- **hide debug markers as default**

## Review Procedure

Screenshot from 2022-09-01 13-15-15

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
- [x]  make pull_over debug marker as `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/pullover`
  - https://github.com/autowarefoundation/autoware.universe/pull/1843
- [x] remove old rviz configuration
  - https://github.com/tier4/autoware_launch/pull/480

**Comment by kosuke55** [comment]
@satoshi-ota 
Could you please update awf's one https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/rviz/autoware.rviz ?

**Comment by satoshi-ota** [comment]
@kosuke55 I created PR in awf/autoware_launch. https://github.com/autowarefoundation/autoware_launch/pull/85

**Pull request merged**
