### PR TITLE
fix(localization_launch): fix input topic name

### PR DESCRIPTION
**Pull request by YamatoAndo**
## PR Type

- Bug Fix

## Description
Changed from `rectified/pointcloud` to `outlier_filtered/pointcloud`, due to the change in https://github.com/tier4/aip_launcher/pull/24.

## Review Procedure
make sure that localization module works well

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets
- [x] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by taikitanaka3 — APPROVED** [review]
I approve this change for xx1.

**Review by 0x126 — APPROVED** [review]
LGTM

**Comment by taikitanaka3** [comment]
@YamatoAndo 
Can you write this to release note and merge?

cc : @yukkysaito @h-ohta

**Review by yukkysaito — APPROVED** [review]

**Comment by h-ohta** [comment]
@taikitanaka3 Sorry for late reply. In S1, `input/pointcloud` argument is overrided in autoware.launch.xml like below.
https://github.com/tier4/autoware_launch.s1/blob/tier4/universe/autoware_launch/launch/autoware.launch.xml#L68-L88

**Pull request merged**
