### PR TITLE
refactor: virtual wall rviz config

### PR DESCRIPTION
**Pull request by TakaHoribe**
Copy of https://github.com/autowarefoundation/autoware_launch/pull/42

### CODE REVIEW

**Comment by yukkysaito** [comment]
@TakaHoribe Why are there changes about Perception?

**Comment by TakaHoribe** [comment]
@yukkysaito I see. I just copied rviz config from autowarefoundation/autoware_launch. Is there any reason for using different configs? Or you can pick up the one you want to use.

**Comment by taikitanaka3** [comment]
@yukkysaito 
This old PR was necessary to sync to awf
https://github.com/tier4/autoware_launch/pull/196

@TakaHoribe 
so you need to remove change of perception part by this PR or use rviz config from tier4/autoware_launch

**Comment by yukkysaito** [comment]
@TakaHoribe I see. It is no problem.
LGTM

**Comment by yukkysaito** [comment]
@taikitanaka3 can you create PR for AWF?
after this PR is merged, it may be better to create PR again. :pray:

**Comment by taikitanaka3** [comment]
@yukkysaito 
OK I will create PR for AWF later, after https://github.com/autowarefoundation/autoware_launch/pull/42 is merged

**Comment by TakaHoribe** [comment]
Then I'll merge as this is

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
