### PR TITLE
feat(localization_launch): replace localization_launch with tier4_localization_launch

### PR DESCRIPTION
**Pull request by kminoda**
Signed-off-by: kminoda <koji.minoda@tier4.jp>

## PR Type

- Improvement

## Related Links
Also need to merge https://github.com/tier4/aip_launcher/pull/98

## Description
Remove localization_launch and use tier4_localization_launch in autoware.universe.

The parameter configuration in autoware.universe and autoware_launch has been modified as described in [this issue](https://github.com/autowarefoundation/autoware_launch/issues/66).
With this modification, we are now able to pass parameter paths to tier4_xx_launch from the outside of the package, i.e. autoware_launch packages. Thus, I would like to remove xx_launch from tier4/autoware_launch and replace it with tier4_xx_launch in autoware.universe. 

With this PR, we can reduce the maintenance cost of xx_launch.

(Before this PR: we need to modify both tier4_xx_launch and xx_launch. After this PR: we only need to modify tier4_xx_launch) 

## Remarks
Please refer to this [TIER IV internal link](https://tier4.atlassian.net/wiki/spaces/~727523079/pages/2673279578/tier4+autoware+launch+xx+launch+-+tier4+xx+launch), too.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by YamatoAndo** [comment]
@tkimura4 @h-ohta  I'll leave it to your judgment.

**Comment by h-ohta** [comment]
@kminoda Could you add some reason why you make this PR, e.g. issues etc?

**Comment by takayuki5168** [comment]
The change looks good to me.
It's fine for me to merge if psim and lsim work well with this PR.

**Comment by h-ohta** [comment]
I confirmed starting autoware.launch.xml and logging_simulator.launch.xml

**Review by h-ohta — DISMISSED** [review]

**Comment by kminoda** [comment]
@h-ohta Sorry, would you approve this again?

**Review by h-ohta — DISMISSED** [review]
LGTM.
However, I'd like to discuss how we can understand  easily which parameter is changed in the next step.

**Comment by kminoda** [comment]
@h-ohta Sorry, would you approve this again? :bow:

**Review by h-ohta — DISMISSED** [review]

**Comment by kminoda** [comment]
@YamatoAndo Regarding the issue due to https://github.com/autowarefoundation/autoware.universe/pull/2114, I think there are two solutions
1. Fix aip_launcher and incorporate the modification in https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/48
2. Provide `/sensing/lidar/top/...` as a `pointcloud_container_name` from autoware_launch (no need for modification in aip_launcher)

I thought 2 would be a simple and thus better at least as a temporary solution. What do you think?

**Comment by YamatoAndo** [comment]
@kminoda If it is a temporary solution, option 2 would be fine.

**Review by h-ohta — APPROVED** [review]

**Pull request merged**
