### PR TITLE
feat: sync with autoware launch in awf

### PR DESCRIPTION
**Pull request by yukkysaito**
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>

## PR Type

- Improvement

## Description

I refactor and sync with awf autoware_launch.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [x] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets
- [x] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
image

**Comment by yukkysaito** [comment]
image

**Comment by yukkysaito** [comment]
https://github.com/tier4/autoware_launch/pull/255#issuecomment-1083346329
The above error did not cause when the branch of individual params was set to main.

https://github.com/tier4/pilot-auto/blob/tier4/universe/autoware.proj.repos#L31-L34

cc @TakaHoribe

**Comment by yukkysaito** [comment]
>The above error did not cause when the branch of individual params was set to main.

fixed
https://github.com/tier4/pilot-auto/pull/444

**Comment by yukkysaito** [comment]
@TakaHoribe 
- [x] resolve this error :pray: 
  - https://github.com/tier4/autoware_launch/pull/255#issuecomment-1083353227
- [x] change from control.py to control.xml in autoware_launch
- [x] move lat_controller_param_path into control.launch 
  - https://github.com/tier4/autoware_launch/pull/255/files#diff-50750b08f3020bc2dd51ea26edb44963eac70e078996276ec18859efa308a18bR89

**Comment by TakaHoribe** [comment]
Need to merge https://github.com/tier4/lexus_description.iv/pull/28 to launch vehicle modules

**Comment by yukkysaito** [comment]
TODO 

Make same modifications and send PR to AWF autoware_launch
[a5b112e](https://github.com/tier4/autoware_launch/pull/255/commits/a5b112e85b81ee9898c53128143fd308c137a220)

**Comment by yukkysaito** [comment]
I made the PR to AWF autoware_launch
https://github.com/autowarefoundation/autoware_launch/pull/19

**Review by kenji-miyake — DISMISSED** [review]

**Comment by yukkysaito** [comment]
Please wait a little while until I can confirm that it works.

**Review by kenji-miyake — APPROVED** [review]

**Comment by yukkysaito** [comment]
I confirmed to work
- `ros2 launch autoware_launch planning_simulator.launch.xml map_path:=/sample/map/ vehicle_model:=lexus sensor_model:=aip_xx1`
- `ros2 launch autoware_launch logging_simulator.launch.xml map_path:=/sample/map/ vehicle_model:=lexus sensor_model:=aip_xx1 `

**Pull request merged**
