### PR TITLE
ci: add sync-awf.yaml

### PR DESCRIPTION
**Pull request by kenji-miyake**
To sync `awf-sync` with `tier4/universe`.

### CODE REVIEW

**Comment by kenji-miyake** [comment]
https://github.com/tier4/autoware_launch/runs/6520112616?check_suite_focus=true
-> https://github.com/tier4/autoware_launch/pull/319

**Comment by kenji-miyake** [comment]
We can consider a different name for `awf-sync`, such as `latest`.
Does anyone have an idea? :thinking:

**Comment by tkimura4** [comment]
@kenji-miyake 
How about this

branch: awf-latest
sync-branch sync-awf-latest

**Comment by kenji-miyake** [comment]
Thank you, renamed!

**Review by tkimura4 — APPROVED** [review]

**Pull request merged**
