### PR TITLE
feat: replace roi_cluster_fusion to image_projection_based_fusion

### PR DESCRIPTION
**Pull request by yukke42**
Signed-off-by: yukke42 <yusuke.muramatsu@tier4.jp>

## PR Type

- New Feature

## Related Links

https://github.com/autowarefoundation/autoware.universe/pull/548

## Description

The roi_cluster_fusion package is replaced to image_project_based_fusion.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by miursh** [comment]
@yukke42 Don't you want to add roi_detected_object_fusion after centerpoint?

**Comment by yukke42** [comment]
> @.yukke42 Don't you want to add roi_detected_object_fusion after centerpoint?

@miursh  I plan to do it, but not in this PR.

**Comment by miursh** [comment]
@yukke42 Need to change "output" [here](https://github.com/yukke42/autoware_launch/blob/feature/image-projection-based-fusion/perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml#L83 ) to "output/clusters"

**Comment by yukke42** [comment]
@miursh I fix the problem.

**Review by miursh — APPROVED** [review]
LGTM

**Pull request merged**
