### PR TITLE
perception_launch: Traffic light composable nodes

### PR DESCRIPTION
**Pull request by wep21**
### Related PR
https://github.com/tier4/Pilot.Auto/pull/253
### How to test
- launch perception
`ros2 launch perception_launch perception.launch.xml mode:=lidar`
- clone traffic light dataset publisher(https://github.com/wep21/traffic_light_dataset_publisher) into your workspace and build
- launch dataset publisher
`ros2 launch traffic_light_dataset_publisher traffic_light_dataset_publisher.launch.xml image_folder:=(your_download directory)/voclike_datasets_from_web_noncrop/train/JPEGImages label_folder:=(your_download directory)/voclike_datasets_from_web_noncrop/train/Annotations`
- echo traffic light state
`ros2 topic echo /perception/traffic_light_recognition/traffic_light_states`
- launch rqt image view and check debug image
`ros2 run rqt_image_view`
Screenshot from 2021-01-12 19-19-26
Screenshot from 2021-01-12 20-34-12

### CODE REVIEW

**Comment by k0suke-murakami** [comment]
Could you describe how to check this PR?

**Comment by wep21** [comment]
@k0suke-murakami I've updated the description above. Please check and test.

**Comment by wep21** [comment]
@TakaHoribe Have you already tested this?

**Comment by TakaHoribe** [comment]
@wep21 I could see the debug images as shown in your post.  Also noticed the `perception.launch` died with the following message while checking the data. I'm not sure this is ok or not.
```
[component_container-9] terminate called after throwing an instance of 'cv::Exception'
[component_container-9]   what():  OpenCV(4.2.0) ../modules/core/src/matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
[component_container-9] 
[ERROR] [component_container-9]: process has died [pid 152720, exit code -6, cmd '/opt/ros/foxy/lib/rclcpp_components/component_container --ros-args -r __node:=traffic_light_node_container -r __ns:=/perception/traffic_light_recognition'].
```

**Comment by wep21** [comment]
@TakaHoribe Thank you for checking. I will try to find the cause of exception.

**Comment by TakaHoribe** [comment]
@wep21 This happens every time. It may be the demo data contains invalid data, or the processing at the end of the demo data throws an exception.

**Review by TakaHoribe — APPROVED** [review]
Investigation for the exception problem could be later.

**Pull request merged**
