### PR TITLE
feat(atutoware.rviz): disable selectable for pointcloud visualization

### PR DESCRIPTION
**Pull request by YamatoAndo**
Signed-off-by: YamatoAndo <yamato.ando@gmail.com>

## PR Type

- Improvement

## Description
To make rviz work lighter,  I set the selectable for pointcloud visualization to false.

This PR is remake of https://github.com/tier4/autoware_launcher/pull/468 (private repos)

## Review Procedure
Make sure that when you display a large size pointcloud and move the viewpoint, the rviz works lighter than before.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [x] All open points are addressed and tracked via issues or tickets
- [x] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
@YamatoAndo この問題は結局他の人は再現しなかったのですが、安藤さんは再現したということでしょうか？

**Review by TakaHoribe — APPROVED** [review]
Worked to me.

**Review by h-ohta — APPROVED** [review]
LGTM

**Comment by YamatoAndo** [comment]
@yukkysaito 
> この問題は結局他の人は再現しなかったのですが、安藤さんは再現したということでしょうか？

Yes, it works in my environment.

**Comment by YamatoAndo** [comment]
@yukkysaito Do you have any concerns?

**Comment by yukkysaito** [comment]
>@yukkysaito Do you have any concerns?

LGTM

**Review by yukkysaito — APPROVED** [review]

**Pull request merged**
