### PR TITLE
fix: occ grid topic name

### PR DESCRIPTION
**Pull request by taikitanaka3**
Signed-off-by: tanaka3 <ttatcoder@outlook.jp>

## PR Type

- Bug Fix

## Description

fix occupancy grid map topic name

## Review Procedure

see topic info 

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by tkimura4** [comment]
Maybe, `/perception/occupancy_grid_map/map` is true.

Someway, the remapping does not work correctly. https://github.com/tier4/AutowareArchitectureProposal_launcher/blob/tier4/universe/perception_launch/launch/perception.launch.xml#L52

**Comment by taikitanaka3** [comment]
@tkimura4 
However it seems /perception/obstacle_segmentation/occupancy_grid is published
```
ros2 node info /perception/obstacle_segmentation/occupancy_grid_map_node 
/perception/obstacle_segmentation/occupancy_grid_map_node
  Subscribers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/obstacle_segmentation/concatenated/pointcloud: sensor_msgs/msg/PointCloud2
    /perception/obstacle_segmentation/pointcloud: sensor_msgs/msg/PointCloud2
    /perception/obstacle_segmentation/virtual_scan/laserscan: sensor_msgs/msg/LaserScan
  Publishers:
    /parameter_events: rcl_interfaces/msg/ParameterEvent
    /perception/obstacle_segmentation/occupancy_grid: nav_msgs/msg/OccupancyGrid
    /rosout: rcl_interfaces/msg/Log
  Service Servers:
    /perception/obstacle_segmentation/occupancy_grid_map_node/describe_parameters: rcl_interfaces/srv/DescribeParameters
    /perception/obstacle_segmentation/occupancy_grid_map_node/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
    /perception/obstacle_segmentation/occupancy_grid_map_node/get_parameters: rcl_interfaces/srv/GetParameters
    /perception/obstacle_segmentation/occupancy_grid_map_node/list_parameters: rcl_interfaces/srv/ListParameters
    /perception/obstacle_segmentation/occupancy_grid_map_node/set_parameters: rcl_interfaces/srv/SetParameters
    /perception/obstacle_segmentation/occupancy_grid_map_node/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
  Service Clients:

  Action Servers:

  Action Clients:

```
and there is no occupancy_grid node
```
ros2 topic list |grep perception
/api/iv_msgs/perception/object_recognition/tracking/objects
/perception/object_recognition/detection/labeled_clusters
/perception/object_recognition/detection/objects
/perception/object_recognition/detection/objects_with_feature
/perception/object_recognition/objects
/perception/object_recognition/prediction/objects_path_markers
/perception/object_recognition/tracking/objects
/perception/obstacle_segmentation/concatenated/pointcloud
/perception/obstacle_segmentation/occupancy_grid
/perception/obstacle_segmentation/pointcloud
/perception/obstacle_segmentation/virtual_scan/laserscan
/perception/obstacle_segmentation/virtual_scan/pointcloud
/perception/obstacle_segmentation/virtual_scan/ray
/perception/obstacle_segmentation/virtual_scan/stixel
/perception/occupancy_grid_map/map
/perception/occupancy_grid_map/map_updates
/perception/traffic_light_recognition/debug/rois
/perception/traffic_light_recognition/traffic_light_map_based_detector/debug/markers
/perception/traffic_light_recognition/traffic_signals

```

**Comment by taikitanaka3** [comment]
@yukkysaito 
Do you know what is the final output of occupancy grid map topic name?

**Comment by tkimura4** [comment]
@taikitanaka3 

yes. I checked it.

The issue is that the parameter settings do not work correctly.
https://github.com/tier4/AutowareArchitectureProposal_launcher/blob/tier4/universe/perception_launch/launch/perception.launch.xml#L50-L56

**Comment by taikitanaka3** [comment]
@tkimura4 
So I fixed here.
image
tested in Psim
image

**Comment by yukkysaito** [comment]
@taikitanaka3 
I think the topic name in input is correct before the change.
```
        <arg name="input/obstacle_pointcloud" value="/perception/obstacle_segmentation/single_frame/pointcloud_raw" />
        <arg name="input/raw_pointcloud" value="/sensing/lidar/concatenated/pointcloud" />
```
The output should have the following name
```
/perception/occupancy_grid_map/map
```

**Comment by taikitanaka3** [comment]
@yukkysaito 
> I think the topic name in input is correct before the change.
However I can't see any occupancy grid map in `/perception/occupancy_grid_map/map` so there is still some problem in launch.py

**Comment by taikitanaka3** [comment]
This PR is ncessary instead of this PR
https://github.com/autowarefoundation/autoware.universe/pull/242

**Pull request closed without merging**
